name: "Hola mundo"

on:
  push:
    branches: ["main"]


jobs:
  firts_job:
    name: firts_job_github_actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hola mundo desde GitHub Actions"
      - name: Run a multi-line script
        run: |
          echo "Hola mundo desde GitHub Actions"
          echo "Este es un ejemplo de un script de varias líneas"
  second_job:
    name: second_job_github_actions
    needs: firts_job # This job depends on the completion of the first job
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Ensure this job only runs on push to main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hola mundo desde el segundo job"
      - name: Run a multi-line script
        run: |
          echo "Hola mundo desde el segundo job"
          echo "Este es un ejemplo de un script de varias líneas en el segundo job"
