name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
#    outputs:
#      salida: ${{ steps.step_1.outputs.var }} # Uncomment this line to enable outputs

    steps:
      - name: Crear archivo
        run: echo "Hola mundo" >> test.txt

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.txt

#lo revisas el archivo-test en Artifacts --> github/actions/runs/ en Summary (web del repo)

  segundo_job:
    runs-on: ubuntu-latest
    needs: first_job

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test

      - name: Cat file
        run: cat test.txt