name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo
        run: echo "Hola mundo" >> test.txt
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.txt