name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
##construye un arhivo local con el nombre de test.txt que diga hola mundo()
    steps:
      - name: Crear archivo
        run: echo "Hola mundo" > test.txt

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
